/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Employed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3104977377955340465L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employed\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"years\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employed> ENCODER =
      new BinaryMessageEncoder<Employed>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employed> DECODER =
      new BinaryMessageDecoder<Employed>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Employed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Employed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Employed>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Employed to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Employed from a ByteBuffer. */
  public static Employed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public CharSequence name;
  @Deprecated public Integer years;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employed() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param years The new value for years
   */
  public Employed(Integer id, CharSequence name, Integer years) {
    this.id = id;
    this.name = name;
    this.years = years;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return years;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (Integer)value$; break;
    case 1: name = (CharSequence)value$; break;
    case 2: years = (Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'years' field.
   * @return The value of the 'years' field.
   */
  public Integer getYears() {
    return years;
  }

  /**
   * Sets the value of the 'years' field.
   * @param value the value to set.
   */
  public void setYears(Integer value) {
    this.years = value;
  }

  /**
   * Creates a new Employed RecordBuilder.
   * @return A new Employed RecordBuilder
   */
  public static Employed.Builder newBuilder() {
    return new Employed.Builder();
  }

  /**
   * Creates a new Employed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employed RecordBuilder
   */
  public static Employed.Builder newBuilder(Employed.Builder other) {
    return new Employed.Builder(other);
  }

  /**
   * Creates a new Employed RecordBuilder by copying an existing Employed instance.
   * @param other The existing instance to copy.
   * @return A new Employed RecordBuilder
   */
  public static Employed.Builder newBuilder(Employed other) {
    return new Employed.Builder(other);
  }

  /**
   * RecordBuilder for Employed instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employed>
    implements org.apache.avro.data.RecordBuilder<Employed> {

    private int id;
    private CharSequence name;
    private Integer years;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Employed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.years)) {
        this.years = data().deepCopy(fields()[2].schema(), other.years);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Employed instance
     * @param other The existing instance to copy.
     */
    private Builder(Employed other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.years)) {
        this.years = data().deepCopy(fields()[2].schema(), other.years);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public Employed.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public Employed.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public Employed.Builder setName(CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public Employed.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'years' field.
      * @return The value.
      */
    public Integer getYears() {
      return years;
    }

    /**
      * Sets the value of the 'years' field.
      * @param value The value of 'years'.
      * @return This builder.
      */
    public Employed.Builder setYears(Integer value) {
      validate(fields()[2], value);
      this.years = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'years' field has been set.
      * @return True if the 'years' field has been set, false otherwise.
      */
    public boolean hasYears() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'years' field.
      * @return This builder.
      */
    public Employed.Builder clearYears() {
      years = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employed build() {
      try {
        Employed record = new Employed();
        record.id = fieldSetFlags()[0] ? this.id : (Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (CharSequence) defaultValue(fields()[1]);
        record.years = fieldSetFlags()[2] ? this.years : (Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employed>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employed>
    READER$ = (org.apache.avro.io.DatumReader<Employed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
